import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { AuthProvider } from "@/util/auth-context";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";
import LoadingSpinner from "./cards/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <Suspense fallback={<LoadingSpinner />}>{children}</Suspense>
        </AuthProvider>
      </body>
    </html>
  );
}
